In [8]:
from bs4 import BeautifulSoup
import pandas as pd

In [9]:
fd = open("../datasets/List of countries by GDP (nominal) - Wikipedia.htm", "r", encoding = "utf-8")
soup = BeautifulSoup(fd)
fd.close()

FileNotFoundError: [Errno 2] No such file or directory: '../datasets/List of countries by GDP (nominal) - Wikipedia.htm'

In [ ]:
all_tables = soup.find_all("table")
print("Total number of tables are {} ".format(len(all_tables)))

In [3]:
data_table = soup.find("table", {"class": '"wikitable"|}'})
print(type(data_table))

NameError: name 'soup' is not defined

In [4]:
sources = data_table.tbody.findAll('tr', recursive=False)[0]
sources_list = [td for td in sources.findAll('td')]
print(len(sources_list))

NameError: name 'data_table' is not defined

In [5]:
data = data_table.tbody.findAll('tr', recursive=False)[1].findAll('td', recursive=False)

NameError: name 'data_table' is not defined

In [6]:
data_tables = []
for td in data:
    data_tables.append(td.findAll('table'))

NameError: name 'data' is not defined

In [7]:
len(data_tables)

0

In [9]:
source_names = [source.findAll('a')[0].getText() for source in sources_list]
print(source_names)

['International Monetary Fund', 'World Bank', 'United Nations']

In [10]:
header1 = [th.getText().strip() for th in data_tables[0][0].findAll('thead')[0].findAll('th')]
header1

['Rank', 'Country', 'GDP(US$MM)']

In [11]:
rows1 = data_tables[0][0].findAll('tbody')[0].findAll('tr')

In [12]:
data_rows1 = [[td.get_text().strip() for td in tr.findAll('td')] for tr in rows1]

In [13]:
df1 = pd.DataFrame(data_rows1, columns=header1)
df1.head()

  Rank        Country  GDP(US$MM)
0           World[19]  79,865,481
1    1  United States  19,390,600
2    2     China[n 1]  12,014,610
3    3          Japan   4,872,135
4    4        Germany   3,684,816

In [14]:
header2 = [th.getText().strip() for th in data_tables[1][0].findAll('thead')[0].findAll('th')]
header2

['Rank', 'Country', 'GDP(US$MM)']

In [15]:
rows2 = data_tables[1][0].findAll('tbody')[0].findAll('tr')

In [16]:
def find_right_text(i, td):
    if i == 0:
        return td.getText().strip()
    elif i == 1:
        return td.getText().strip()
    else:
        index = td.text.find("♠")
        return td.text[index+1:].strip()

In [17]:
data_rows2 = [[find_right_text(i, td) for i, td in enumerate(tr.findAll('td'))] for tr in rows2]

In [18]:
df2 = pd.DataFrame(data_rows2, columns=header2)
df2.head()

  Rank             Country  GDP(US$MM)
0                    World  80,683,787
1    1       United States  19,390,604
2       European Union[23]  17,277,698
3    2          China[n 4]  12,237,700
4    3               Japan   4,872,137

In [19]:
header3 = [th.getText().strip() for th in data_tables[2][0].findAll('thead')[0].findAll('th')]
header3

['Rank', 'Country', 'GDP(US$MM)']

In [20]:
rows3 = data_tables[2][0].findAll('tbody')[0].findAll('tr')

In [21]:
data_rows3 = [[find_right_text(i, td) for i, td in enumerate(tr.findAll('td'))] for tr in rows2]

In [22]:
df3 = pd.DataFrame(data_rows3, columns=header3)
df3.head()

  Rank             Country  GDP(US$MM)
0                    World  80,683,787
1    1       United States  19,390,604
2       European Union[23]  17,277,698
3    2          China[n 4]  12,237,700
4    3               Japan   4,872,137